routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'DashboardController@index')->name('dashboard');
Route::get('/movies/get', 'MovieController@get')->name('movies.get');
Route::resources([
    'movies' => 'MovieController',
    'actors' => 'ActorController',
    'producers' => 'ProducerController',
]);

resources/views/pages/movies/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        <create-movie-component :create_movie_url="'{{ route('movies.store')}}'" :create_actor_url="'{{ route('actors.store')}}'" :create_producer_url="'{{ route('producers.store')}}'"
            :actors="{{ $actors }}" :producers="{{ $producers }}"></create-movie-component>
    </div>
@endsection

resources/views/pages/movies/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        <edit-movie-component :update_movie_url="'{{ route('movies.update', [$movie->id])}}'" :movie="{{ $movie }}" :actors="{{ $actors }}" :producers="{{ $producers }}"></edit-movie-component>
    </div>
@endsection

resources/views/pages/movies/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        <list-movie-component :get_movie_url="'{{ route('movies.get') }}'"></list-movie-component>
    </div>
@endsection

resources/views/pages/movies/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card shadow mb-4">
                    <div class="card-header py-3">
                        <b>Movie Details</b>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered">
                                <tbody>
                                    <tr>
                                        <td>Name</td>
                                        <td>{{ $movie->name }}</td>
                                    </tr>
                                    <tr>
                                        <td>Year Of Release</td>
                                        <td>{{ $movie->year_of_release }}</td>
                                    </tr>
                                    <tr>
                                        <td>Plot</td>
                                        <td>{{ $movie->plot }}</td>
                                    </tr>
                                    <tr>
                                        <td>Poster</td>
                                        <td><img style="width: 200px;" src="{{ $movie->poster }}"></td>
                                    </tr>
                                    <tr>
                                        <td>Created At</td>
                                        <td>{{ $movie->created_at }}</td>
                                    </tr>
                                    <tr>
                                        <td>Updated At</td>
                                        <td>{{ $movie->updated }}</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="card shadow mb-4">
                    <div class="card-header py-3">
                        <b>Producer</b>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered">
                                <tbody>
                                    <tr>
                                        <td>Name</td>
                                        <td>{{ $movie->producer->name }}</td>
                                    </tr>
                                    <tr>
                                        <td>Sex</td>
                                        <td>{{ $movie->producer->sex }}</td>
                                    </tr>
                                    <tr>
                                        <td>Date Of Birth</td>
                                        <td>{{ $movie->producer->dob }}</td>
                                    </tr>
                                    <tr>
                                        <td>Bio</td>
                                        <td>{{ $movie->producer->bio }}</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="card shadow mb-4">
                    <div class="card-header py-3">
                        <b>List Of Actor</b>
                    </div>
                    <div class="card-body">
                        @foreach ($movie->actors as $key => $actor)
                            <div style="font-size: 16px;" class="mb-3 badge badge-primary">Actor {{ $key + 1 }}</div>
                            <div class="table-responsive mb-4">
                                <table class="table table-bordered">
                                    <tbody>
                                    <tr>
                                        <td>Name</td>
                                        <td>{{ $actor->name }}</td>
                                    </tr>
                                    <tr>
                                        <td>Sex</td>
                                        <td>{{ $actor->sex }}</td>
                                    </tr>
                                    <tr>
                                        <td>Date Of Birth</td>
                                        <td>{{ $actor->dob }}</td>
                                    </tr>
                                    <tr>
                                        <td>Bio</td>
                                        <td>{{ $actor->bio }}</td>
                                    </tr>
                                    </tbody>
                                </table>
                            </div>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection